# Generated by Django 4.2.7 on 2025-07-19 19:33

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[core.validators.validate_phone_number], verbose_name='Teléfono'),
        ),
    ]
