# Generated by Django 4.2.7 on 2025-07-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='temp/', verbose_name='Imagen principal (subir archivo)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL de imagen principal'),
        ),
    ]
