# Generated by Django 4.2.7 on 2025-07-19 19:33

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_main_image_alter_product_main_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image_url',
            field=models.URLField(blank=True, null=True, validators=[core.validators.validate_url_format], verbose_name='URL de imagen'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image_url',
            field=models.URLField(blank=True, null=True, validators=[core.validators.validate_url_format], verbose_name='URL de imagen principal'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[core.validators.validate_positive_price], verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, validators=[core.validators.validate_non_negative_stock], verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_url',
            field=models.URLField(validators=[core.validators.validate_url_format], verbose_name='URL de imagen'),
        ),
    ]
